# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml 2>&1 | tee build.log

    - name: Send logs to MCP
      env:
        MCP_SERVER_URL: ${{ secrets.MCP_SERVER_URL }}
      run: |
        if [ -n "$MCP_SERVER_URL" ]; then
          curl -X POST "$MCP_SERVER_URL/ingest" --data-binary @build.log
        else
          echo "MCP_SERVER_URL not set; skipping sending logs"
        fi
